platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
- name: feed-resource
  path: .

outputs:
- name: image

caches:
- path: cache

params:
  DOCKERFILE: docker/Dockerfile

run:
  path: build
